[package]
name = "gba"
description = "A crate for making GBA games with Rust."
version = "0.6.0"
authors = ["Lokathor <zefria@gmail.com>", "Thomas Winwood <twwinwood@gmail.com>"]
repository = "https://github.com/rust-console/gba"
readme = "README.md"
keywords = ["gba"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

publish = false

[dependencies]
voladdress = "1"
bytemuck = "1"
embedded-hal = { version = "0.2.4", optional = true }
nb = { version = "1", optional = true }

[features]
default = []
serial = ["embedded-hal", "nb"]

# most examples are fine with defaults, but uart_echo needs an extra feature
[[example]]
name = "uart_echo"
required-features = ["serial"]

[profile.dev]
panic = "abort"
opt-level = 3
lto = true

[profile.release]
panic = "abort"
lto = true

[package.metadata.docs.rs]
default-target = "thumbv4t-none-eabi"
cargoflags = ["-Zbuild-std=core"]
rustdoc-args = ["--cfg","docs_rs"]
