[package]
name = "gba"
version = "0.6.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

publish = false

[dependencies]
voladdress = "1"
bytemuck = "1"

[profile.dev]
panic = "abort"
opt-level = 3
lto = true

[profile.release]
panic = "abort"
lto = true
